#!/usr/bin/env nextflow

nextflow.enable.dsl=2

/*
Important (18.11.21):
I am trying to implement the parallelization logic to the process. So, at this point, I am trying to not print any of the files into the workspace anymore because there are obviously multiple files generated by philosopher and msfraggger (such as .pepXML, .pep.xml and so on). These multiple files would probably interfere with each other and the .meta directory. So, for now, I will just separate the processes processing the different input files completely with nextflow logic. (namely: doing all the nextflow processes in the work subdirectories for each input file separately)
*/


process WORKSPACE {
    
    label 'philosopher'

    input:
    path mzML_file

    output:
    stdout

    script:
    """
    input=\$(basename ${mzML_file})
    prefix=\$(echo \$input | cut -d '_' -f 1)

    mkdir -p ${projectDir}/\$prefix

    mv ${projectDir}/${mzML_file} ${projectDir}/\$prefix

    cd ${projectDir}/\$prefix

    philosopher workspace --clean
    philosopher workspace --init

    echo ${projectDir}/\$prefix/\$input
    """

}

process DATABASE {

    label 'philosopher'
    
    publishDir "${params.outDir}/database", mode: 'copy'

    input:
    each new_mzML
    path db

    output:
    path '*.fas'

    script:
    """
    # extract prefix from each mzML_file
    input=\$(basename ${new_mzML})
    prefix=\$(echo \$input | cut -d '_' -f 1)

    # initialize philosopher in current wd and run command
    philosopher workspace --init
    philosopher database --custom ${db} --contam

    # execute the same command in subdirectory of workspace for each input file for philosopher to run properly
    cd ${projectDir}/\$prefix
    philosopher workspace --init
    philosopher database --custom ${db} --contam
    """

}

process GENERATEPARAMS {

    label 'msfragger'

    publishDir "${params.outDir}/generateparams", mode: 'copy'

    input:
    path mzML_file
    path db
    
    output:
    path 'closed_fragger.params'

    script:
    """
    # extract prefix from each mzML_file
    input=\$(basename ${mzML_file})
    prefix=\$(echo \$input | cut -d '_' -f 1)

    java -jar /MSFragger.jar --config
    cp closed_fragger.params ${projectDir}/\$prefix
    """

}

process CHANGEFILE {

    publishDir "${params.outDir}/changefile", mode: 'copy'

    input:
    path mzML_file
    path db
    path closed_fragger
    
    output:
    path 'closed_fragger.params'

    script:
    """
    input=\$(basename ${mzML_file})
    prefix=\$(echo \$input | cut -d '_' -f 1)

    python ${projectDir}/change_file.py ${db} ${closed_fragger}
    cp closed_fragger.params ${projectDir}/\$prefix
    """

}

process MSFRAGGER {

    //label "msfragger"

    //def directory = ${mzML_file}
    //.substring(0, input.lastIndexOf("_"))

    publishDir "${params.outDir}/msfragger/", mode: 'copy'

    input:
    path mzML_file
    path closed_fragger
    path db_file

    output:
    path '*.pepXML'

    /*
    MSFragger is doing some stupid stuff again: it outputs the .pepXML file right next to the mzML file. So, the data files must absolutely just plainly be in the workspace directory.

    So, I devised a strategy: I move the mzML files into the directory where msfragger nextflow is working on, so I am sure that the pepXML files will be output right in the work directory. After this step, I will move the mzML files back into the workspace.
    */
    
    script:
    """
    # move mzML file into this nextflow work directory
    # mv ${mzML_file} .
    
    # capture the file name without the path and the prefix
    input=\$(basename ${mzML_file})
    prefix=\$(echo \$input | cut -d '_' -f 1)

    # execute MSFragger on the mzML file (output will be located in this work dir)
    java -Xmx8g -jar ${projectDir}/MSFragger/MSFragger.jar ${closed_fragger} ${mzML_file}

    # move mzML file back to the workspace
    #mv \$input ${projectDir}

    # copy all files into a directory named as the input file's prefix
    #rsync -aP --exclude="\$prefix" . \$prefix
    #shopt -s extglob
    #rm -rf !(\$prefix)
    
    # change into specific input file directory again
    # mv ${mzML_file} ${projectDir}/\$prefix

    #cp ${mzML_file} ${projectDir}/\$prefix

    cd ${projectDir}/\$prefix

    java -Xmx8g -jar ${projectDir}/MSFragger/MSFragger.jar ${closed_fragger} \$input
    #mv \$input ${projectDir}

    # copy only .pepXML files from the workspace to this work directory
    #rsync -aP --include='*.pepXML' --exclude='*' ${projectDir}/. \$workd
    """

}

process PEPTIDEPROPHET {
    
    label "philosopher"

    publishDir "${params.outDir}/peptideprophet", mode: 'copy'
       
    input:
    path db
    path pepXML
    
    output:
    path "*.pep.xml"
    
    script:
    """
    input=\$(basename ${pepXML})
    prefix=\$(echo \$input | cut -d '_' -f 1)
    
    cp -r ${projectDir}/\$prefix/.meta .
    philosopher peptideprophet --database ${db} --decoy rev_ --ppm --accmass --expectscore --decoyprobs --nonparam --output \$prefix \$input

    # execute command in specific workspace sub directory (prefix)
    cd ${projectDir}/\$prefix
    philosopher peptideprophet --database ${db} --decoy rev_ --ppm --accmass --expectscore --decoyprobs --nonparam --output \$prefix \$input 2> \$prefix.peptideprophet
    """

}

process PROTEINPROPHET {
    
    label "philosopher"

    publishDir "${params.outDir}/proteinprophet", mode: 'copy'
       
    input:
    path pepxml
    
    output:
    path "*.prot.xml"
     
    script:
    """
    workd=\$(pwd)
    input=\$(basename ${pepxml})
    prefix=\$(echo \$input | cut -d '-' -f 1)

    cp -r ${projectDir}/\$prefix/.meta .
    mv ${projectDir}/\$prefix/*.pep.xml .
    #rsync -av --include='*.pep.xml' ${projectDir}/\$prefix .
    philosopher proteinprophet --output \$prefix ${pepxml}
    mv *.pep.xml ${projectDir}/\$prefix

    cp ${projectDir}/\$prefix/\$prefix.prot.xml \$workd

    cd ${projectDir}/\$prefix
    philosopher proteinprophet --output \$prefix ${pepxml} 2> \$prefix.proteinprophet
    """

}

process FILTERANDFDR {
    
    label "philosopher"

    publishDir "${params.outDir}/filterandfdr", mode: 'copy'

    input:
    path pepxml
    path protXML

    output:
    path '*.filterandfdr', emit: filter_file
    path protXML, emit: protXML
     
    script:
    """
    input=\$(basename ${protXML})
    prefix=\$(echo \$input | cut -d '.' -f 1)

    cp -r ${projectDir}/\$prefix/.meta .
    philosopher filter --sequential --razor --picked --tag rev_ --pepxml ${pepxml} --protxml ${protXML} 2> \$prefix.filterandfdr

    cd ${projectDir}/\$prefix
    philosopher filter --sequential --razor --picked --tag rev_ --pepxml ${pepxml} --protxml ${protXML} 2> \$prefix.filterandfdr
    """

}

process QUANTIFY {
    
    label "philosopher"

    publishDir "${params.outDir}/quantify", mode: 'copy'

    input:
    path filter
    path protXML

    output:
    //path '*.quantify'
    path '*'
    
    script:
    """
    # capture prefix of input files
    input=\$(basename ${protXML})
    prefix=\$(echo \$input | cut -d '.' -f 1)

    # copy files to nextflow work directory
    cp -r ${projectDir}/\$prefix/. .
    #philosopher freequant --dir . 2> \$prefix.quantify

    #cd ${projectDir}/\$prefix
    #philosopher freequant --dir . 2> \$prefix.quantify
    """

}

process REPORT {
    
    label "philosopher"

    publishDir "${params.outDir}/report", mode: 'copy'

    input:
    path quant

    output:
    path '*.report'
     
    script:
    """
    # capture prefix of input files
    input=\$(basename ${protXML})
    prefix=\$(echo \$input | cut -d '.' -f 1)

    cp -r ${projectDir}/\$prefix/. .
    philosopher report 2> \$prefix.report

    cd ${projectDir}/\$prefix
    philosopher report 2> \$prefix.report
    """

}

/*
command to be executed from workspace directory: nextflow run containers.nf -profile docker -with-report -with-trace -with-timeline -with-dag dag.png

The msfragger container doesn't have ps installed, so it is not possible to run this pipeline with the -with-report option. A possible solution is suggested on https://github.com/replikation/What_the_Phage/issues/89.
*/

workflow {

    input_ch = Channel.fromPath(params.input)
    db_ch = Channel.of(params.db)
    input_ch.view()

    workspace_obj = WORKSPACE(input_ch)

    db_obj = DATABASE(workspace_obj, db_ch)

    params_obj = GENERATEPARAMS(workspace_obj, db_obj)

    change_obj = CHANGEFILE(workspace_obj, db_obj, params_obj)

    pepXML_obj = MSFRAGGER(workspace_obj, change_obj, db_obj)

    pepdotxml_obj = PEPTIDEPROPHET(db_obj, pepXML_obj)

    protXML_obj = PROTEINPROPHET(pepdotxml_obj)

    filter_obj = FILTERANDFDR(pepdotxml_obj, protXML_obj)

    quant_obj = QUANTIFY(FILTERANDFDR.out.filter_file, FILTERANDFDR.out.protXML)
    quant_obj.view()
    
    /*
    report_obj = REPORT(quant_obj)
    */

}
