#!/usr/bin/env nextflow

nextflow.enable.dsl=2


/*

https://github.com/Nesvilab/philosopher/wiki/Simple-Data-Analysis

A couple important notes and observations:

docker run -it --rm --volume $HOME:$HOME --workdir $PWD prvst/philosopher
-> This command allows you to run your philosopher analysis inside of a docker container, it also mounts your machine's files inside of the virtual docker container. The container is then able to read and write files in your machine's environment

*/


params.parentDir = "/Users/noepozzan/Documents/unibas/nesvilab"
params.input_file = "002_TSP7-21_D19.mzML"
params.input_noext = "002_TSP7-21_D19"
params.input = "${projectDir}/${params.input_file}"
input_ch = Channel.fromPath(params.input)
params.proteome_ID = "UP000000589"
ID_ch = Channel.of(params.proteome_ID)
params.outDir = "results"
params.fragRAM = 4


log.info """\
     P R O T E O M I C S   P I P E L I N E    
     =====================================
     parentDir    : ${params.parentDir}
     projectDir   : ${projectDir}
     input        : ${params.input}
     proteome ID  : ${params.proteome_ID}
     outDir       : ${params.outDir}
     fragger RAM  : ${params.fragRAM}

     """
     .stripIndent()


/*
 1. Create a workspace

The workspace will be named "workspace" in the base directory of the project and (!!) run this whole philosopher analysis from the "workspace" directory
-> this seems to be unnecessary, since the initialization of philosopher has to be done at every process step, since every process loads up a new container.
*/

process WORKSPACE {

    label "philosopher"
    container 'prvst/philosopher:4.0.0'

    script:       
    """
    philosopher workspace --clean
    philosopher workspace --init
    """
}

/*
2. Download a protein database

Proteome ID of mus musculus is UP000000589
This process generates a new file in the workspace directory, that I should somehow automatically catch
*/

process DATABASE {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/database", mode: 'copy'
         
    input:
    val x

    output:
    file '*'
    
    script:
    """
    philosopher workspace --init
    philosopher database --id $x --contam --reviewed
    """
}

/*
3. Perform a database search with MSFragger

This command runs a docker container to convert a .raw file to a .mzML file.
docker run -it --rm -v $HOME:$HOME chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert /Users/noepozzan/Documents/unibas/nesvilab/002_TSP7-21_D19.raw -o /Users/noepozzan/Documents/unibas/nesvilab
-> seems to produce a corrupted file or something, that is why I pulled a mzML file (001_TPP7-21_C19.mzML) from Meric's scicore repository, which works with MSFragger

This command runs a docker container to use MSFragger.
docker run -it --volume $HOME:$HOME singjust/msfragger:3.1.1
Inside of the docker container, you run:
java -Xmx4g -jar MSFragger.jar /Users/noepozzan/Documents/unibas/nesvilab/closed_fragger.params /Users/noepozzan/Documents/unibas/nesvilab/workspace/002_TSP7-21_D19.mzML
Additionally, the database file generated by philosopher has to be present in the directory, from which this command is run.
-> actually, the container is not able to produce the pepXML file, while the cl app is(?)

The CHANGEFILE process is really bad concerning reproducibility and will have to be fixed.
*/

process CHANGEFILE {

    input:
    path db
    
    output:
    path closed_fragger

    script:
    """
    python ${params.parentDir}/change_file.py ${db} > closed_fragger
    """

}

process MSFRAGGER {

    label "msfragger"
    
    container 'singjust/msfragger:3.1.1'

    publishDir "${params.outDir}/msfragger", mode: 'copy'

    input:
    path db_obj
    path mzML_file
    path db_file

    output:
    path '*.pepXML'

    shell:
    """
    java -Xmx${params.fragRAM}g -jar /MSFragger.jar ${} ${mzML_file}

    java -Xmx4g -jar /Users/noepozzan/Documents/unibas/nesvilab/MSFragger/MSFragger.jar /Users/noepozzan/Documents/unibas/nesvilab/workspace/closed_fragger.params /Users/noepozzan/Documents/unibas/nesvilab/workspace/001_TPP7-21_C19.mzML
    """
}

/*
4. PeptideProphet

This step validates the peptide hits found by MSFragger.
*/

process PEPTIDEPROPHET {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/peptideprophet", mode: 'copy'
       
    input:
    path db
    path pepXML 
    
    output:
    path "interact-${params.input_noext}.pep.xml"
    
     
    script:
    """
    philosopher workspace --init
    philosopher peptideprophet --database ${db} --decoy rev_ --ppm --accmass --expectscore --decoyprobs --nonparam ${pepXML} 
    """
}

/*
5. ProteinProphet

This step performs protein inference.
*/

process PROTEINPROPHET {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/proteinprophet", mode: 'copy'
       
    input:
    path pepxml
    
    output:
    path '*.prot.xml'
     
    script:
    """
    philosopher workspace --init
    philosopher proteinprophet ${pepxml}
    """
}

/*
6. Filter and estimate FDR

*/

process FILTERANDFDR {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/filterandfdr", mode: 'copy'
       
    input:
    path pepxml
    path protXML
    
    output:
    path "filterfdr_output.txt"
     
    script:
    """
    philosopher workspace --init
    philosopher filter --sequential --razor --picked --tag rev_ --pepxml ${pepxml} --protxml ${protXML} > filterfdr_output.txt
    """
}

/*
7. Quantification

*/

process QUANTIFY {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/quantify", mode: 'copy'
    
    script:
    """
    philosopher workspace --init
    philosopher freequant --dir .
    """
}

/*
8. Generate a report

*/

process REPORT {
    
    label "philosopher"

    container 'prvst/philosopher:4.0.0'

    publishDir "${params.outDir}/report", mode: 'copy'
     
    script:
    """
    philosopher workspace --init
    philosopher report
    """
}


workflow {
    
    //WORKSPACE()
    db_obj = DATABASE(ID_ch)
    params_obj = CHANGEFILE(db_obj)
    pepXML_obj = MSFRAGGER(input_ch, params_obj)
    pepdotxml_obj = PEPTIDEPROPHET(db_obj, pepXML_obj)
    protXML_obj = PROTEINPROPHET(pepdotxml_obj)
    filter_obj = FILTERANDFDR(pepdotxml_obj, protXML_obj)
    filter_obj.view()

    /*
    QUANTIFY()
    REPORT()
    */

}




